### ISSUE TITLE
Consider using Result

### ISSUE THREAD

**Issue by enthusiastmartin** [galacticcouncil/HydraDX-math#3]
Might be better returning Result instead of option for better and more clear error handling

**Comment by RoboRambo** [comment]
[Rust Docs](https://doc.rust-lang.org/rust-by-example/error.html) state:
`The Option type is for when a value is optional or when the lack of a value is not an error condition.`
and also
`When there is a chance that things do go wrong and the caller has to deal with the problem, use Result.`

If we check usages like [here](https://github.com/galacticcouncil/HydraDX-node/blob/master/pallets/amm/src/lib.rs), we can see that: 

1. in lib.rs:540: if result of calculate_spot_price is None, then we will map None to zero.
2. in lib.rs:602: if result of calculate_spot_price is None, then we will map None to Error.

Maybe this is as designed however if we return Option and treat several different exceptional cases as one, it might be too much of a burden for a client to figure out how to deal with this one exceptional case. Also, we might be able to deliver a better usability as exceptional states can be better handled and communicated to the user.

**I would argue for returning Result.**
Since the math crate will only be used in this context, we might as well define exceptional cases there.

Please correct me if I'm wrong.

**Comment by enthusiastmartin** [comment]
#6
